language: node_js

# never build when commited by the bot
if: sender != "styleguidist-bot" AND (type = pull_request OR branch = master)

node_js:
  - 10
  - 8
  - 6

addons:
  apt:
    packages:
      - libgconf-2-4

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install --ignore-engines

script:
  # Run tests without coverage since it's 2x faster
  - yarn test:jest --runInBand

# Trigger a push build on master branches only + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master

stages:
  - lint
  - test
  - typecheck
  - integration
  - coverage
  - name: release
    if: type != pull_request AND branch = master
  - name: documentation
    if: type != pull_request AND branch = master
jobs:
  include:
    - stage: lint
      script:
        - yarn lint
        - npx danger ci

    - stage: typecheck
      script:
        - yarn flow check

    - stage: integration
      script:
        # Compile JS
        - yarn compile
        # Build all examples
        - yarn build:basic
        - yarn build:customised
        - yarn build:sections
        # Check that examples really works: no JS errors on load
        - yarn test:browser:pre
        - yarn test:browser:basic
        - yarn test:browser:customised
        - yarn test:browser:sections
        # Run integration tests with Cypress
        - yarn test:cypress:pre
        - yarn test:cypress:startServer &
        - yarn test:cypress:startServer:post
        - yarn test:cypress:run

    - stage: coverage
      script:
        # Run tests with coverage
        - yarn test:coverage --runInBand
        # Upload coverage report to Codecov
        - bash <(curl -s https://codecov.io/bash)

    - stage: release
      script:
        - yarn compile
        - git config --global user.name "Styleguidist Bot"
        - git config --global user.email "artem+styleguidist@sapegin.ru"
        - git remote set-url origin "https://${GH_TOKEN}@github.com/styleguidist/react-styleguidist.git" > /dev/null 2>&1
        - git checkout master
        - git reset --hard
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
        - yarn lerna version --yes --github-release
        - yarn lerna publish from-git --yes

    - stage: documentation
      script:
        - curl -X POST -d '{}' https://api.netlify.com/build_hooks/591308eba700c425fc1e8a54
